#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

# Update package lists
apt-get update -y

# Install Nginx
apt-get install -y nginx

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

# Restart Nginx
service nginx restart
# sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
