#!/usr/bin/env bash
# The pkill -f command searches for processes whose command line matches the provided pattern and terminates them. In this case, it will search for processes with the command line containing "4-to_infinity_and_beyond" and stop them
# If the command is successful, the processes will be terminated. If there are no matching processes, the pkill command will have no effect.
# pkill -f 4-to_infinity_and_beyond or pkill -f "4-to_infinity_and_beyond" works

pkill -f "4-to_infinity_and_beyond"
